FROM ubuntu:latest
RUN apt update && apt install -y zip
RUN apt install -y python
RUN apt install -y python3.7
RUN apt install -y default-jdk
RUN apt-get install -y gcc
RUN apt install -y python3-pip
