FROM gcc
FROM java:8-jdk-alpine
FROM ubuntu:latest
FROM python
RUN apt update && apt install -y zip
ADD /files.zip /
RUN unzip files.zip && rm files.zip
FROM gcc
FROM java:8-jdk-alpine
FROM ubuntu:latest
FROM python
RUN apt update && apt install -y zip
ADD /files.zip /
RUN unzip files.zip && rm files.zip
FROM gcc
FROM java:8-jdk-alpine
FROM ubuntu:latest
FROM python
RUN apt update && apt install -y zip
ADD /files.zip /
RUN unzip files.zip && rm files.zip
FROM gcc
FROM java:8-jdk-alpine
FROM ubuntu:latest
FROM python
RUN apt update && apt install -y zip
ADD /files.zip /
RUN unzip files.zip && rm files.zip
FROM gcc
FROM java:8-jdk-alpine
FROM ubuntu:latest
FROM python
RUN apt update && apt install -y zip
ADD /files.zip /
RUN unzip files.zip && rm files.zip
FROM gcc
FROM java:8-jdk-alpine
FROM ubuntu:latest
FROM python
RUN apt update && apt install -y zip
ADD /files.zip /
RUN unzip files.zip && rm files.zip
