FROM ubuntu:latest
RUN apt update && apt install -y zip
RUN apt install -y python
RUN apt install -y default-jdk
RUN apt-get install -y gcc
RUN apt-get install -y python-pip
RUN apt-get install -y python3-pip
RUN apt-get install -y openmpi-bin
